apiVersion: v1
data:
  {{- with .Values.imagePullSecret }}
  imagePullSecret: {{ . }}
  {{- end }}
  platform-name: {{ default "OpenDataHub" (index .Values.config "platform-name") | quote }}
  platform-version: {{ default "unknown" (index .Values.config "platform-version") | quote }}
  {{- range $key, $val := .Values.config }}
  {{- if and (ne $key "platform-name") (ne $key "platform-version") }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-ray-operator
  name: opendatahub-ray-config
  namespace: {{ .Release.Namespace }}