apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymodule-workload
  labels:
    app: mymodule-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymodule-workload
  template:
    metadata:
      labels:
        app: mymodule-workload
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
