apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-orchestrator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
  labels:
    app.kubernetes.io/name: opendatahub-orchestrator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opendatahub-orchestrator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: opendatahub-orchestrator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        - operator
        image: ttl.sh/opendatahub-orchestrator:1h
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /etc/controller/config
          readOnly: true
        env:
        - name: ODH_MODULE_OPERATOR_CONFIGURATION_PATH
          value: /etc/controller/config
        - name: ODH_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: config
        configMap:
          name: config
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
