config:
  platform-type: OpenDataHub
  platform-version: unknown
image:
  pullPolicy: Always
  repository: ttl.sh/opendatahub-module-operator
  tag: 1h
leaderElect: true
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
serviceAccount: {}
