variants:
  odh:
    manifests:
      kustomize:
        - path: manifests
          contextDir: workbenches/odh-notebook-controller
          sourcePath: base
          params:
            - file: params.env
              replaceFromEnv:
                odh-notebook-controller-image: RELATED_IMAGE_ODH_NOTEBOOK_CONTROLLER_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
        - path: manifests
          contextDir: workbenches/kf-notebook-controller
          sourcePath: overlays/openshift
          params:
            - file: params.env
              replaceFromEnv:
                odh-kf-notebook-controller-image: RELATED_IMAGE_ODH_KF_NOTEBOOK_CONTROLLER_IMAGE
        - path: manifests
          contextDir: workbenches/notebooks
          sourcePath: odh/overlays/additional
        - path: manifests
          contextDir: workbenches/notebooks
          sourcePath: odh/base
          skipRender: true
          params:
            - file: params-latest.env
              replaceFromEnv:
                odh-workbench-codeserver-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_CODESERVER_DATASCIENCE_CPU_PY312_IMAGE
                odh-workbench-jupyter-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_DATASCIENCE_CPU_PY312_IMAGE
                odh-workbench-jupyter-minimal-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_CPU_PY312_IMAGE
                odh-workbench-jupyter-minimal-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_CUDA_PY312_IMAGE
                odh-workbench-jupyter-minimal-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_ROCM_PY312_IMAGE
                odh-workbench-jupyter-pytorch-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_CUDA_PY312_IMAGE
                odh-workbench-jupyter-pytorch-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_ROCM_PY312_IMAGE
                odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TENSORFLOW_CUDA_PY312_IMAGE
                odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TENSORFLOW_ROCM_PY312_IMAGE
                odh-workbench-jupyter-trustyai-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TRUSTYAI_CPU_PY312_IMAGE
                odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_LLMCOMPRESSOR_CUDA_PY312_IMAGE
                odh-pipeline-runtime-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_DATASCIENCE_CPU_PY312_IMAGE
                odh-pipeline-runtime-minimal-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_MINIMAL_CPU_PY312_IMAGE
                odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_TENSORFLOW_CUDA_PY312_IMAGE
                odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_TENSORFLOW_ROCM_PY312_IMAGE
                odh-pipeline-runtime-pytorch-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_CUDA_PY312_IMAGE
                odh-pipeline-runtime-pytorch-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_ROCM_PY312_IMAGE
                odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_LLMCOMPRESSOR_CUDA_PY312_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  rhoai:
    manifests:
      kustomize:
        - path: manifests
          contextDir: workbenches/odh-notebook-controller
          sourcePath: base
          params:
            - file: params.env
              replaceFromEnv:
                odh-notebook-controller-image: RELATED_IMAGE_ODH_NOTEBOOK_CONTROLLER_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
        - path: manifests
          contextDir: workbenches/kf-notebook-controller
          sourcePath: overlays/openshift
          params:
            - file: params.env
              replaceFromEnv:
                odh-kf-notebook-controller-image: RELATED_IMAGE_ODH_KF_NOTEBOOK_CONTROLLER_IMAGE
        - path: manifests
          contextDir: workbenches/notebooks
          sourcePath: odh/overlays/additional
        - path: manifests
          contextDir: workbenches/notebooks
          sourcePath: odh/base
          skipRender: true
          params:
            - file: params-latest.env
              replaceFromEnv:
                odh-workbench-codeserver-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_CODESERVER_DATASCIENCE_CPU_PY312_IMAGE
                odh-workbench-jupyter-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_DATASCIENCE_CPU_PY312_IMAGE
                odh-workbench-jupyter-minimal-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_CPU_PY312_IMAGE
                odh-workbench-jupyter-minimal-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_CUDA_PY312_IMAGE
                odh-workbench-jupyter-minimal-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_MINIMAL_ROCM_PY312_IMAGE
                odh-workbench-jupyter-pytorch-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_CUDA_PY312_IMAGE
                odh-workbench-jupyter-pytorch-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_ROCM_PY312_IMAGE
                odh-workbench-jupyter-tensorflow-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TENSORFLOW_CUDA_PY312_IMAGE
                odh-workbench-jupyter-tensorflow-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TENSORFLOW_ROCM_PY312_IMAGE
                odh-workbench-jupyter-trustyai-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_TRUSTYAI_CPU_PY312_IMAGE
                odh-workbench-jupyter-pytorch-llmcompressor-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_WORKBENCH_JUPYTER_PYTORCH_LLMCOMPRESSOR_CUDA_PY312_IMAGE
                odh-pipeline-runtime-datascience-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_DATASCIENCE_CPU_PY312_IMAGE
                odh-pipeline-runtime-minimal-cpu-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_MINIMAL_CPU_PY312_IMAGE
                odh-pipeline-runtime-tensorflow-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_TENSORFLOW_CUDA_PY312_IMAGE
                odh-pipeline-runtime-tensorflow-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_TENSORFLOW_ROCM_PY312_IMAGE
                odh-pipeline-runtime-pytorch-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_CUDA_PY312_IMAGE
                odh-pipeline-runtime-pytorch-rocm-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_ROCM_PY312_IMAGE
                odh-pipeline-runtime-pytorch-llmcompressor-cuda-py312-ubi9-n: RELATED_IMAGE_ODH_PIPELINE_RUNTIME_PYTORCH_LLMCOMPRESSOR_CUDA_PY312_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
