apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-modelregistry-operator
  name: opendatahub-modelregistry-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opendatahub-modelregistry-manager-role
subjects:
- kind: ServiceAccount
  name: {{ default (include "chart.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opendatahub-modelregistry-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opendatahub-modelregistry-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ default (include "chart.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}