apiVersion: v1
data:
  {{- with .Values.imagePullSecret }}
  imagePullSecret: {{ . }}
  {{- end }}
  platformVersion: {{ default "" (index .Values.config "platformVersion") | quote }}
  {{- range $key, $val := .Values.config }}
  {{- if ne $key "platformVersion" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-spark-operator
  name: odh-spark-config
  namespace: {{ .Release.Namespace }}