variants:
  odh:
    manifests:
      kustomize:
        - path: manifests
          contextDir: trustyai
          sourcePath: overlays/odh
          params:
            - file: params.env
              replaceFromEnv:
                trustyaiServiceImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE
                trustyaiOperatorImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_OPERATOR_IMAGE
                lmes-driver-image: RELATED_IMAGE_ODH_TA_LMES_DRIVER_IMAGE
                lmes-pod-image: RELATED_IMAGE_ODH_TA_LMES_JOB_IMAGE
                guardrails-orchestrator-image: RELATED_IMAGE_ODH_FMS_GUARDRAILS_ORCHESTRATOR_IMAGE
                guardrails-sidecar-gateway-image: RELATED_IMAGE_ODH_TRUSTYAI_VLLM_ORCHESTRATOR_GATEWAY_IMAGE
                guardrails-built-in-detector-image: RELATED_IMAGE_ODH_BUILT_IN_DETECTOR_IMAGE
                ragas-provider-image: RELATED_IMAGE_ODH_PYTHON_312_IMAGE
                garak-provider-image: RELATED_IMAGE_ODH_TRUSTYAI_GARAK_LLS_PROVIDER_DSP_IMAGE
                nemo-guardrails-image: RELATED_IMAGE_ODH_TRUSTYAI_NEMO_GUARDRAILS_SERVER_IMAGE
                evalHubImage: RELATED_IMAGE_ODH_EVAL_HUB_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  rhoai:
    manifests:
      kustomize:
        - path: manifests
          contextDir: trustyai
          sourcePath: overlays/rhoai
          params:
            - file: params.env
              replaceFromEnv:
                trustyaiServiceImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE
                trustyaiOperatorImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_OPERATOR_IMAGE
                lmes-driver-image: RELATED_IMAGE_ODH_TA_LMES_DRIVER_IMAGE
                lmes-pod-image: RELATED_IMAGE_ODH_TA_LMES_JOB_IMAGE
                guardrails-orchestrator-image: RELATED_IMAGE_ODH_FMS_GUARDRAILS_ORCHESTRATOR_IMAGE
                guardrails-sidecar-gateway-image: RELATED_IMAGE_ODH_TRUSTYAI_VLLM_ORCHESTRATOR_GATEWAY_IMAGE
                guardrails-built-in-detector-image: RELATED_IMAGE_ODH_BUILT_IN_DETECTOR_IMAGE
                ragas-provider-image: RELATED_IMAGE_ODH_PYTHON_312_IMAGE
                garak-provider-image: RELATED_IMAGE_ODH_TRUSTYAI_GARAK_LLS_PROVIDER_DSP_IMAGE
                nemo-guardrails-image: RELATED_IMAGE_ODH_TRUSTYAI_NEMO_GUARDRAILS_SERVER_IMAGE
                evalHubImage: RELATED_IMAGE_ODH_EVAL_HUB_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  mcp-guardrails:
    manifests:
      kustomize:
        - path: manifests
          contextDir: trustyai
          sourcePath: overlays/mcp-guardrails
          params:
            - file: params.env
              replaceFromEnv:
                trustyaiServiceImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_IMAGE
                trustyaiOperatorImage: RELATED_IMAGE_ODH_TRUSTYAI_SERVICE_OPERATOR_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
                nemo-guardrails-image: RELATED_IMAGE_ODH_TRUSTYAI_NEMO_GUARDRAILS_SERVER_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
