variants:
  odh:
    manifests:
      kustomize:
        - path: manifests
          contextDir: feastoperator
          sourcePath: overlays/odh
          params:
            - file: params.env
              replaceFromEnv:
                RELATED_IMAGE_FEAST_OPERATOR: RELATED_IMAGE_ODH_FEAST_OPERATOR_IMAGE
                RELATED_IMAGE_FEATURE_SERVER: RELATED_IMAGE_ODH_FEATURE_SERVER_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  rhoai:
    manifests:
      kustomize:
        - path: manifests
          contextDir: feastoperator
          sourcePath: overlays/rhoai
          params:
            - file: params.env
              replaceFromEnv:
                RELATED_IMAGE_FEAST_OPERATOR: RELATED_IMAGE_ODH_FEAST_OPERATOR_IMAGE
                RELATED_IMAGE_FEATURE_SERVER: RELATED_IMAGE_ODH_FEATURE_SERVER_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
