apiVersion: v1
data:
  {{- with .Values.imagePullSecret }}
  imagePullSecret: {{ . }}
  {{- end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-orchestrator
  name: opendatahub-orchestrator-config
  namespace: {{ .Release.Namespace }}