apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opendatahub-orchestrator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.opendatahub.io
  resources:
  - platformoperators
  - platforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.opendatahub.io
  resources:
  - platformoperators/status
  - platforms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.opendatahub.io
  resources:
  - platforms/finalizers
  verbs:
  - update