apiVersion: components.platform.opendatahub.io/v1alpha1
kind: DataSciencePipelines
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-datasciencepipelines-operator
  name: default-datasciencepipelines
spec: {}
