apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odh-db-operator-manager-role
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - infrastructure.opendatahub.io
  resources:
  - databaseclaims
  - databaseproviders
  - schemaclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.opendatahub.io
  resources:
  - databaseclaims/finalizers
  - databaseproviders/finalizers
  - schemaclaims/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.opendatahub.io
  resources:
  - databaseclaims/status
  - databaseproviders/status
  - schemaclaims/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.platform.opendatahub.io
  resources:
  - databaseservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.platform.opendatahub.io
  resources:
  - databaseservices/finalizers
  verbs:
  - update
- apiGroups:
  - services.platform.opendatahub.io
  resources:
  - databaseservices/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odh-db-operator-metrics-auth-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odh-db-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get