apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: DatabaseProvider
metadata:
  name: sample-internal
spec:
  type: Internal
  internal:
    namespace: opendatahub-db
    deletionPolicy: Retain
    storage:
      size: 10Gi
    extensions:
    - vector
    - pg_trgm
