apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: DatabaseClaim
metadata:
  name: sample-database
  namespace: team-a
spec:
  provider:
    name: sample-external
  secretName: sample-database-credentials
  database: mlmd
  access: ReadWrite
