apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opendatahub-mymodule-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - opendatahub-mymodule-webhook-service.{{ .Release.Namespace }}.svc
  - opendatahub-mymodule-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: opendatahub-mymodule-selfsigned-issuer
  secretName: webhook-server-cert