config: {}
imagePullSecrets: []
operator:
  image:
    pullPolicy: Always
    ref: ttl.sh/opendatahub-trainer-operator:latest
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
platform:
  type: OpenDataHub
  version: ""
serviceAccount: {}
