variants:
  odh:
    manifests:
      kustomize:
        - path: manifests
          contextDir: trainer
          sourcePath: rhoai
          params:
            - file: params.env
              replaceFromEnv:
                odh-kubeflow-trainer-controller-image: RELATED_IMAGE_ODH_TRAINER_IMAGE
                odh-training-cuda128-torch29-py312-image: RELATED_IMAGE_ODH_TRAINING_CUDA128_TORCH29_PY312_IMAGE
                odh-training-rocm64-torch29-py312-image: RELATED_IMAGE_ODH_TRAINING_ROCM64_TORCH29_PY312_IMAGE
                odh-th06-cuda130-torch210-py312-image: RELATED_IMAGE_ODH_TH06_CUDA130_TORCH210_PY312_IMAGE
                odh-th06-rocm64-torch291-py312-image: RELATED_IMAGE_ODH_TH06_ROCM64_TORCH291_PY312_IMAGE
                odh-th06-cpu-torch210-py312-image: RELATED_IMAGE_ODH_TH06_CPU_TORCH210_PY312_IMAGE
                odh-training-universal-workbench-image-cuda-3-4: RELATED_IMAGE_ODH_TH06_CUDA130_TORCH210_PY312_IMAGE
                odh-training-universal-workbench-image-rocm-3-4: RELATED_IMAGE_ODH_TH06_ROCM64_TORCH291_PY312_IMAGE
                odh-training-universal-workbench-image-cpu-3-4: RELATED_IMAGE_ODH_TH06_CPU_TORCH210_PY312_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  rhoai:
    manifests:
      kustomize:
        - path: manifests
          contextDir: trainer
          sourcePath: rhoai
          params:
            - file: params.env
              replaceFromEnv:
                odh-kubeflow-trainer-controller-image: RELATED_IMAGE_ODH_TRAINER_IMAGE
                odh-training-cuda128-torch29-py312-image: RELATED_IMAGE_ODH_TRAINING_CUDA128_TORCH29_PY312_IMAGE
                odh-training-rocm64-torch29-py312-image: RELATED_IMAGE_ODH_TRAINING_ROCM64_TORCH29_PY312_IMAGE
                odh-th06-cuda130-torch210-py312-image: RELATED_IMAGE_ODH_TH06_CUDA130_TORCH210_PY312_IMAGE
                odh-th06-rocm64-torch291-py312-image: RELATED_IMAGE_ODH_TH06_ROCM64_TORCH291_PY312_IMAGE
                odh-th06-cpu-torch210-py312-image: RELATED_IMAGE_ODH_TH06_CPU_TORCH210_PY312_IMAGE
                odh-training-universal-workbench-image-cuda-3-4: RELATED_IMAGE_ODH_TH06_CUDA130_TORCH210_PY312_IMAGE
                odh-training-universal-workbench-image-rocm-3-4: RELATED_IMAGE_ODH_TH06_ROCM64_TORCH291_PY312_IMAGE
                odh-training-universal-workbench-image-cpu-3-4: RELATED_IMAGE_ODH_TH06_CPU_TORCH210_PY312_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
