apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: odh-workbenches-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - odh-workbenches-webhook-service.{{ .Release.Namespace }}.svc
  - odh-workbenches-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: odh-workbenches-selfsigned-issuer
  secretName: webhook-server-cert