apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-workbenches-operator
  name: odh-workbenches-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: opendatahub-workbenches-operator
---
apiVersion: v1
kind: Service
metadata:
  name: odh-workbenches-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: opendatahub-workbenches-operator