apiVersion: v1
data:
  platformType: {{ default "OpenDataHub" .Values.platform.type | quote }}
  platformVersion: {{ default "" .Values.platform.version | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: opendatahub-workbenches-operator
  name: odh-workbenches-config
  namespace: {{ .Release.Namespace }}