resources:
- bases/infrastructure.opendatahub.io_databaseclaims.yaml
- bases/infrastructure.opendatahub.io_databaseproviders.yaml
- bases/infrastructure.opendatahub.io_schemaclaims.yaml
- bases/services.platform.opendatahub.io_databaseservices.yaml
