name: Module Tests

on:
  push:
    paths:
      - "modules/**"
      - ".github/workflows/test-modules.yml"
      - ".github/workflows/module-test.yml"
  pull_request:
    paths:
      - "modules/**"
      - ".github/workflows/test-modules.yml"
      - ".github/workflows/module-test.yml"

permissions: {}

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    name: Detect changed modules
    runs-on: ubuntu-latest
    outputs:
      mymodule: ${{ steps.filter.outputs.mymodule }}
      ray: ${{ steps.filter.outputs.ray }}
      spark: ${{ steps.filter.outputs.spark }}
      feast: ${{ steps.filter.outputs.feast }}
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Detect changed module paths
        id: filter
        uses: dorny/paths-filter@v4.0.0
        with:
          filters: |
            mymodule:
              - 'modules/opendatahub-mymodule-operator/**'
            ray:
              - 'modules/opendatahub-ray-operator/**'
            spark:
              - 'modules/opendatahub-spark-operator/**'
            feast:
              - 'modules/opendatahub-feast-operator/**'

  test-mymodule:
    name: opendatahub-mymodule-operator
    needs: changes
    if: ${{ needs.changes.outputs.mymodule == 'true' }}
    uses: ./.github/workflows/module-test.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      module_name: opendatahub-mymodule-operator
      module_path: modules/opendatahub-mymodule-operator
      image_name: opendatahub-mymodule-operator

  test-ray:
    name: opendatahub-ray-operator
    needs: changes
    if: ${{ needs.changes.outputs.ray == 'true' }}
    uses: ./.github/workflows/module-test.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      module_name: opendatahub-ray-operator
      module_path: modules/opendatahub-ray-operator
      image_name: opendatahub-ray-operator

  test-spark:
    name: opendatahub-spark-operator
    needs: changes
    if: ${{ needs.changes.outputs.spark == 'true' }}
    uses: ./.github/workflows/module-test.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      module_name: opendatahub-spark-operator
      module_path: modules/opendatahub-spark-operator
      image_name: opendatahub-spark-operator

  test-feast:
    name: opendatahub-feast-operator
    needs: changes
    if: ${{ needs.changes.outputs.feast == 'true' }}
    uses: ./.github/workflows/module-test.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      module_name: opendatahub-feast-operator
      module_path: modules/opendatahub-feast-operator
      image_name: opendatahub-feast-operator
