variants:
  odh:
    manifests:
      kustomize:
        - path: manifests
          contextDir: datasciencepipelines
          sourcePath: overlays/odh
        - path: manifests
          contextDir: datasciencepipelines
          sourcePath: base
          skipRender: true
          params:
            - file: params.env
              replaceFromEnv:
                IMAGES_DSPO: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_OPERATOR_CONTROLLER_IMAGE
                IMAGES_APISERVER: RELATED_IMAGE_ODH_ML_PIPELINES_API_SERVER_V2_IMAGE
                IMAGES_PERSISTENCEAGENT: RELATED_IMAGE_ODH_ML_PIPELINES_PERSISTENCEAGENT_V2_IMAGE
                IMAGES_SCHEDULEDWORKFLOW: RELATED_IMAGE_ODH_ML_PIPELINES_SCHEDULEDWORKFLOW_V2_IMAGE
                IMAGES_ARGO_EXEC: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_ARGOEXEC_IMAGE
                IMAGES_ARGO_WORKFLOWCONTROLLER: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_WORKFLOWCONTROLLER_IMAGE
                IMAGES_DRIVER: RELATED_IMAGE_ODH_ML_PIPELINES_DRIVER_IMAGE
                IMAGES_LAUNCHER: RELATED_IMAGE_ODH_ML_PIPELINES_LAUNCHER_IMAGE
                IMAGES_MLMDGRPC: RELATED_IMAGE_ODH_MLMD_GRPC_SERVER_IMAGE
                IMAGES_PIPELINESRUNTIMEGENERIC: RELATED_IMAGE_ODH_ML_PIPELINES_RUNTIME_GENERIC_IMAGE
                IMAGES_MLMDENVOY: RELATED_IMAGE_DSP_PROXYV2_IMAGE
                IMAGES_MARIADB: RELATED_IMAGE_DSP_MARIADB_IMAGE
                IMAGES_TOOLBOX: RELATED_IMAGE_DSP_TOOLBOX_IMAGE
                IMAGES_RHELAI: RELATED_IMAGE_DSP_INSTRUCTLAB_NVIDIA_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
                IMAGES_PIPELINES_COMPONENTS: RELATED_IMAGE_ODH_PIPELINES_COMPONENTS_IMAGE
                RELATED_IMAGE_ODH_AUTOML_IMAGE: RELATED_IMAGE_ODH_AUTOML_IMAGE
                RELATED_IMAGE_ODH_AUTORAG_IMAGE: RELATED_IMAGE_ODH_AUTORAG_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
  rhoai:
    manifests:
      kustomize:
        - path: manifests
          contextDir: datasciencepipelines
          sourcePath: overlays/rhoai
        - path: manifests
          contextDir: datasciencepipelines
          sourcePath: base
          skipRender: true
          params:
            - file: params.env
              replaceFromEnv:
                IMAGES_DSPO: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_OPERATOR_CONTROLLER_IMAGE
                IMAGES_APISERVER: RELATED_IMAGE_ODH_ML_PIPELINES_API_SERVER_V2_IMAGE
                IMAGES_PERSISTENCEAGENT: RELATED_IMAGE_ODH_ML_PIPELINES_PERSISTENCEAGENT_V2_IMAGE
                IMAGES_SCHEDULEDWORKFLOW: RELATED_IMAGE_ODH_ML_PIPELINES_SCHEDULEDWORKFLOW_V2_IMAGE
                IMAGES_ARGO_EXEC: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_ARGOEXEC_IMAGE
                IMAGES_ARGO_WORKFLOWCONTROLLER: RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_ARGO_WORKFLOWCONTROLLER_IMAGE
                IMAGES_DRIVER: RELATED_IMAGE_ODH_ML_PIPELINES_DRIVER_IMAGE
                IMAGES_LAUNCHER: RELATED_IMAGE_ODH_ML_PIPELINES_LAUNCHER_IMAGE
                IMAGES_MLMDGRPC: RELATED_IMAGE_ODH_MLMD_GRPC_SERVER_IMAGE
                IMAGES_PIPELINESRUNTIMEGENERIC: RELATED_IMAGE_ODH_ML_PIPELINES_RUNTIME_GENERIC_IMAGE
                IMAGES_MLMDENVOY: RELATED_IMAGE_DSP_PROXYV2_IMAGE
                IMAGES_MARIADB: RELATED_IMAGE_DSP_MARIADB_IMAGE
                IMAGES_TOOLBOX: RELATED_IMAGE_DSP_TOOLBOX_IMAGE
                IMAGES_RHELAI: RELATED_IMAGE_DSP_INSTRUCTLAB_NVIDIA_IMAGE
                kube-rbac-proxy: RELATED_IMAGE_ODH_KUBE_RBAC_PROXY_IMAGE
                IMAGES_PIPELINES_COMPONENTS: RELATED_IMAGE_ODH_PIPELINES_COMPONENTS_IMAGE
                RELATED_IMAGE_ODH_AUTOML_IMAGE: RELATED_IMAGE_ODH_AUTOML_IMAGE
                RELATED_IMAGE_ODH_AUTORAG_IMAGE: RELATED_IMAGE_ODH_AUTORAG_IMAGE
      templates:
        - path: manifests/ext/openshift-config-grants.yaml.tmpl
